name: Development Build

on: workflow_dispatch
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
        
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build-dev:
    name: Dev Build for ${{ matrix.targetPlatform }} with unity version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.9f1
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: BLaZeKiLL/unity-builder@fix/unity-alias
        with:
          customImage: unityci/editor:2020.1.9f1-android-0
          versioning: Semantic
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Editor.Build.AndroidBuilder.DevelopmentBuild
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build