name: Development Build

on: workflow_dispatch
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
        
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} with unity version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.6f
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: webbertakken/unity-builder@v1.4
        with:
          versioning: Semantic
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build